ADAPTER_MCP_PATH = "/mcp"
ADAPTER_HEALTH_PATH = "/healthz"
ADAPTER_READY_PATH = "/readyz"
ADAPTER_SHUTDOWN_PATH = "/shutdown"

WARDN_RUNTIME_COMMAND_ENV = "WARDN_RUNTIME_COMMAND"
WARDN_RUNTIME_ARGS_JSON_ENV = "WARDN_RUNTIME_ARGS_JSON"
WARDN_RUNTIME_CWD_ENV = "WARDN_RUNTIME_CWD"
WARDN_RUNTIME_STARTUP_TIMEOUT_SECONDS_ENV = "WARDN_RUNTIME_STARTUP_TIMEOUT_SECONDS"
WARDN_RUNTIME_REQUEST_TIMEOUT_SECONDS_ENV = "WARDN_RUNTIME_REQUEST_TIMEOUT_SECONDS"

DEFAULT_ADAPTER_PORT = 8000


def adapter_url(endpoint_url: str, path: str) -> str:
    return f"{endpoint_url.rstrip('/')}/{path.lstrip('/')}"
