"""Reviewed legacy log templates; arguments are intentionally never formatted.

New application events should use fixed snake_case names and allowlisted extras.
"""

LEGACY_MESSAGES = {
    "Accepted membership invitation.",
    "Activated %s committed managed-secret provisioning records.",
    "Adding curated MCP server %s.",
    "Agent run resume job failed permanently.",
    "Agent run resume job failed.",
    "Agent run resume worker iteration failed.",
    "Agent tool approval execution failed.",
    "Authenticated OIDC user.",
    "Authenticated local user.",
    "Automatic license renewal failed; the installed lease remains in effect.",
    "Bootstrapped superuser.",
    "Catalog request timed out or could not connect; retrying.",
    "Catalog request was rate limited or temporarily unavailable; retrying.",
    "Claimed MCP operation job cleanup.",
    "Claimed MCP operation job.",
    "Cleaned managed secret %s.",
    "Cleaning MCP server installation artifacts.",
    "Cleanup for managed secret %s failed.",
    "Completed MCP catalog source sync.",
    "Completed MCP installed server bulk update.",
    "Completed MCP operation job cleanup.",
    "Completed MCP operation job.",
    "Completed MCP package installer command: %s in %s.",
    "Completed MCP server installation.",
    "Completed agent run resume job.",
    "Completed scheduled task run.",
    "Continuing agent chat after MCP tool refresh failures; cached tools remain eligible.",
    "Could not fetch README for %s/%s: %s",
    ("Could not immediately queue cleanup for managed secret %s; "
     "the stale-provisioning worker will retry it."),
    "Could not persist MCP operation cleanup failure after lease loss.",
    "Could not persist MCP operation cleanup success after lease loss.",
    "Could not persist MCP operation job failure after lease loss.",
    "Could not persist MCP operation job success after lease loss.",
    "Created Kubernetes MCP runtime Deployment.",
    "Created Kubernetes MCP runtime Ingress.",
    "Created Kubernetes MCP runtime NetworkPolicy.",
    "Created Kubernetes MCP runtime Secret.",
    "Created Kubernetes MCP runtime Service.",
    "Created Kubernetes MCP runtime namespace.",
    "Created LLM provider credential.",
    "Created MCP catalog source token handle.",
    "Created MCP catalog source.",
    "Created MCP runtime session.",
    "Created MCP server version.",
    "Created OIDC user.",
    "Created organization.",
    "Created secret handle.",
    "Created secret store.",
    "Created user API token.",
    "Created user.",
    "Created workspace.",
    "Curated MCP server add failed: %s",
    "Curated MCP server database operation failed: %s",
    "Database readiness check failed",
    "Deferred database work failed.",
    "Deleted Kubernetes MCP runtime Deployment.",
    "Deleted Kubernetes MCP runtime Ingress.",
    "Deleted Kubernetes MCP runtime NetworkPolicy.",
    "Deleted Kubernetes MCP runtime Secret.",
    "Deleted Kubernetes MCP runtime Service.",
    "Deleted LLM provider credential.",
    "Deleted MCP catalog source.",
    "Deleted MCP installation runtime resources.",
    "Deleted MCP server version.",
    "Deleted secret handle.",
    "Deleted secret store.",
    "Deleted user API token.",
    "Deleted workspace.",
    "Deleting Kubernetes MCP runtime resources.",
    "Deleting MCP installation runtime resources.",
    "Dry run complete: %s server versions validated.",
    "Enqueued %s due scheduled task runs.",
    "Externalized MCP install secrets.",
    "Externalizing MCP install secrets.",
    "Failed %s stale orphaned agent runs.",
    "Failed to deliver approval resume reply to chat provider.",
    "Failed to finalize agent chat stream.",
    "Failed to process Slack chat provider message.",
    "Failed to process Telegram chat provider message.",
    "Failed to process WhatsApp chat provider message.",
    "Failed to record MCP server install telemetry.",
    "Failed to record agent chat stream error.",
    "Failed to refresh chat provider typing indicator.",
    "Failed to refresh wildcard MCP server tools; cached tools remain eligible.",
    "Failed to send chat provider progress update.",
    "Failed to start chat provider typing indicator.",
    "Failed to stop chat provider typing indicator.",
    "Failed to submit MCP Hub tool inventory proposal.",
    "Fetched %s registry pages (%s server versions).",
    "Fetched registry page %s: %s entries, %s unique in fetch, %s repeated in fetch.",
    "Fetching %s Wardn Hub version detail documents with concurrency %s.",
    "Fetching MCP catalog source URL.",
    "Fetching registry page %s, cursor=%s",
    "Finalized %s resolved scheduled task approval waits.",
    "Finished MCP catalog source URL.",
    "Finished paged registry fetch after %s pages.",
    "Finished paged registry fetch after empty page %s.",
    "Finished registry fetch after %s pages.",
    "Installed MCP server tool discovery failed",
    "Installed MCP server.",
    "Installing MCP server runtime.",
    "Kubernetes MCP runtime namespace already exists.",
    "Kubernetes runtime network discovery call failed.",
    "LLM OAuth secret value write failed.",
    "Loaded %s supported MCP server entries from file.",
    "Loading supported MCP servers from file: %s",
    "Loading supported MCP servers from registry: %s",
    "Lost MCP operation job cleanup lease.",
    "Lost MCP operation job lease.",
    "Lost agent run resume job lease.",
    "Lost scheduled task run lease.",
    "Lost the cleanup lease for managed secret %s.",
    "MCP catalog source URL failed.",
    "MCP catalog source sync failed.",
    "MCP catalog source sync job failed.",
    "MCP install secret externalization failed.",
    "MCP install secret handle creation failed.",
    "MCP operation job cleanup failed.",
    "MCP operation job failed.",
    "MCP operation job progress: %s",
    "MCP operation worker failed: %s",
    "MCP operation worker iteration failed.",
    "MCP package installer command failed: %s in %s.",
    "MCP package installer command is unavailable: %s in %s.",
    "MCP package installer command timed out: %s in %s.",
    "MCP registry database sync failed: %s",
    "MCP registry sync complete: %s server versions synced.",
    "MCP registry sync failed: %s",
    "MCP runtime reaper database operation failed: %s",
    "MCP runtime reaper deleted %s expired events.",
    "MCP runtime reaper deleted %s expired tool invocations.",
    "MCP runtime reaper disabled.",
    "MCP runtime reaper failed: %s",
    "MCP runtime reaper iteration failed.",
    "MCP runtime reaper recovered %s stale tool invocations.",
    "MCP runtime reaper stopped %s expired sessions.",
    ("MCP runtime reaper stopped %s sessions, deleted %s runtime events, "
     "and deleted %s tool invocations."),
    "MCP runtime startup warmup complete: warmed=%s skipped=%s failed=%s.",
    "MCP runtime startup warmup disabled.",
    "MCP runtime startup warmup failed for installation %s.",
    "MCP runtime startup warmup skipped for provider %s.",
    "MCP runtime warmup failed.",
    "MCP runtime warmup succeeded.",
    "MCP server installation target failed.",
    "MCP server installation validation failed.",
    "MCP tool discovery failed.",
    "MCP tool discovery succeeded.",
    "MCP tool invocation completed.",
    "MCP tool invocation failed.",
    "MCP tool refresh database operation failed: %s",
    "MCP tool refresh failed: %s",
    "MCP tool schema refresh complete for %s: %s tools.",
    "Managed-secret cleanup worker iteration failed.",
    "Membership invitation email mismatch.",
    "OIDC callback failed: %s",
    "OIDC callback failed: missing state cookie",
    "OIDC callback returned provider error",
    "Preparing MCP catalog source sync job.",
    "Preparing MCP server installation target.",
    "Queued %s stale agent run approval resume jobs.",
    "Queued MCP catalog source sync.",
    "Queued MCP installed-server updates.",
    "Queued MCP operation job.",
    "Queued MCP server installation.",
    "Reactivated MCP server version.",
    "Reaping expired MCP runtime sessions, limit %s.",
    "Reconciled Kubernetes MCP runtime.",
    "Reconciling Kubernetes MCP runtime.",
    "Reconnected ChatGPT OAuth credential.",
    "Recorded MCP server install telemetry.",
    "Recovered %s expired MCP operation job leases.",
    "Recovered %s expired agent run resume job leases.",
    "Recovered %s expired managed-secret cleanup leases.",
    "Recovered %s expired scheduled task run leases.",
    "Refreshed ChatGPT OAuth credential.",
    "Refreshed MCP installation tools.",
    "Refreshing ChatGPT OAuth credential.",
    "Refreshing MCP installation tools.",
    "Refreshing MCP tool schemas for %s.",
    "Replaced ChatGPT OAuth credential tokens.",
    "Replaced Kubernetes MCP runtime Deployment.",
    "Replaced Kubernetes MCP runtime Ingress.",
    "Replaced Kubernetes MCP runtime NetworkPolicy.",
    "Replaced Kubernetes MCP runtime Secret.",
    "Replaced Kubernetes MCP runtime Service.",
    "Replaced MCP runtime session.",
    "Replacing ChatGPT OAuth credential tokens.",
    "Resolved MCP install secret handles.",
    "Resolved secret handle.",
    "Retrying ChatGPT Codex websocket after clean round drop.",
    "Reused MCP runtime session after concurrent creation.",
    "Reused MCP runtime session.",
    "Reusing active MCP operation job after enqueue race.",
    "Reusing active MCP operation job.",
    "Reusing active MCP server installation job.",
    "Scaled Kubernetes MCP runtime Deployment.",
    "Scaling Kubernetes MCP runtime deployment to stop runtime.",
    "Scheduled task run failed.",
    "Scheduled task worker iteration failed.",
    "Secret cleanup worker failed: %s",
    "Secret value write failed.",
    "Set default MCP server version.",
    "Skipping MCP runtime reaper; another worker owns maintenance.",
    "Skipping MCP runtime warmup; another worker owns startup maintenance.",
    "Skipping Slack Socket Mode stream because Slack team id is not configured.",
    "Skipping Slack identity hydration; bot token resolution failed.",
    "Skipping WhatsApp bridge stream because bridge user id is not numeric.",
    "Slack Socket Mode stream failed; reconnecting.",
    "Slack identity hydration failed.",
    "Started ChatGPT device authorization.",
    "Started MCP tool invocation.",
    "Starting MCP catalog source sync.",
    "Starting MCP installed server bulk update.",
    "Starting MCP operation job cleanup.",
    "Starting MCP operation job.",
    "Starting MCP package installer command: %s in %s.",
    "Starting MCP registry sync from %s registry, page size %s.",
    "Starting MCP registry sync from file.",
    "Starting MCP runtime for installation.",
    "Starting MCP runtime reaper with %s second interval and batch size %s.",
    "Starting MCP runtime startup warmup.",
    "Starting MCP runtime warmup.",
    "Starting MCP server installation.",
    "Starting MCP tool discovery.",
    "Starting agent run resume job.",
    "Starting isolated MCP operation worker %s.",
    "Starting scheduled task run.",
    "Stopped MCP runtime session.",
    "Stopped after %s registry pages.",
    "Stopped registry fetch because cursor did not advance: %s",
    "Stopped registry fetch because page only repeated earlier entries.",
    "Submitted MCP Hub tool inventory proposal.",
    "Synced MCP catalog source batch.",
    "Synchronized MCP catalog source.",
    "Synchronizing MCP catalog source.",
    "Unable to finalize failed MCP tool invocation %s.",
    "Unable to load Wardn Hub catalog source auth for tool metadata lookup.",
    "Unable to load Wardn Hub tool metadata; falling back to runtime discovery.",
    "Unhandled request error",
    "Uninstalled MCP server configuration.",
    "Uninstalled MCP server.",
    "Uninstalling MCP server configuration.",
    "Uninstalling MCP server.",
    "Updated LLM provider credential.",
    "Updated MCP catalog source.",
    "Updated MCP install secrets in place.",
    "Updated MCP installed server.",
    "Updated MCP server version.",
    "Updated organization.",
    "Updated secret handle.",
    "Updated secret store.",
    "Updated user API token.",
    "Updated workspace assistant model.",
    "Updated workspace assistant personality.",
    "Updated workspace.",
    "Updating MCP installed server.",
    "Upserted MCP catalog server batch.",
    "Validated MCP installation tool.",
    "Validated secret handle.",
    "Validated secret store.",
    "Validating MCP installation tool.",
    "WhatsApp bridge delivery failed; reconnecting session before retry.",
    "WhatsApp bridge event stream failed; reconnecting.",
    "Writing %s server versions to database.",
    "Writing secret values.",
    "Wrote LLM OAuth secret values.",
    "Wrote secret values.",
}
