"""Compatibility facade for MCP registry application services.

New code should import the focused catalog, configuration, installation, or scope
service directly. This facade keeps existing commands and extensions stable during
the boundary migration.
"""

from app.modules.limits import service as limits_service
from app.modules.mcp_registry import repository, tool_repository
from app.modules.mcp_registry.catalog_service import (
    CATALOG_SOURCE_META_KEY,
    CatalogSourceTokenHandle,
    catalog_source_auth_headers,
    catalog_source_metadata,
    catalog_source_payload,
    catalog_source_response,
    catalog_source_stored_base_url,
    catalog_source_token_display_name,
    catalog_source_token_path,
    catalog_source_urls,
    comparable_version_parts,
    compare_version_numbers,
    create_catalog_source,
    create_catalog_source_token_handle,
    create_server_version,
    delete_catalog_source,
    delete_server_version,
    get_catalog_source,
    get_version,
    list_catalog_sources,
    list_servers,
    list_versions,
    official_metadata,
    pulse_metadata,
    registry_metadata,
    registry_source_type,
    server_response,
    server_update_available,
    server_values,
    set_default_server_version,
    sync_catalog_source,
    sync_supported_servers,
    update_catalog_source,
    update_server_version,
    wardn_hub_catalog_url,
)
from app.modules.mcp_registry.config_service import (
    externalize_install_config_secrets,
    install_config_values_from_secret_references,
    merged_install_config_values,
    persist_install_secret_references,
    public_configured_values,
    resolve_install_config_values,
    secret_references_from_runtime_secret_config,
    validate_package_runtime_install,
)
from app.modules.mcp_registry.installation_service import (
    first_text_content,
    install_server_version,
    installation_response,
    list_installation_tools,
    list_installations,
    tool_schema_response,
    uninstall_installation,
    uninstall_server,
    update_installed_servers,
    validate_installation_tool,
    validation_error_from_result,
)
from app.modules.mcp_registry.scope_service import (
    catalog_organization_id,
    default_organization_id,
    default_workspace_id,
    organization_id_for_workspace,
)

__all__ = (
    "CATALOG_SOURCE_META_KEY",
    "CatalogSourceTokenHandle",
    "catalog_organization_id",
    "catalog_source_auth_headers",
    "catalog_source_metadata",
    "catalog_source_payload",
    "catalog_source_response",
    "catalog_source_stored_base_url",
    "catalog_source_token_display_name",
    "catalog_source_token_path",
    "catalog_source_urls",
    "compare_version_numbers",
    "comparable_version_parts",
    "create_catalog_source",
    "create_catalog_source_token_handle",
    "create_server_version",
    "default_organization_id",
    "default_workspace_id",
    "delete_catalog_source",
    "delete_server_version",
    "externalize_install_config_secrets",
    "first_text_content",
    "get_catalog_source",
    "get_version",
    "install_config_values_from_secret_references",
    "install_server_version",
    "installation_response",
    "limits_service",
    "list_catalog_sources",
    "list_installation_tools",
    "list_installations",
    "list_servers",
    "list_versions",
    "merged_install_config_values",
    "official_metadata",
    "organization_id_for_workspace",
    "persist_install_secret_references",
    "public_configured_values",
    "pulse_metadata",
    "registry_metadata",
    "registry_source_type",
    "repository",
    "resolve_install_config_values",
    "secret_references_from_runtime_secret_config",
    "server_response",
    "server_update_available",
    "server_values",
    "set_default_server_version",
    "sync_catalog_source",
    "sync_supported_servers",
    "tool_repository",
    "tool_schema_response",
    "uninstall_installation",
    "uninstall_server",
    "update_catalog_source",
    "update_installed_servers",
    "update_server_version",
    "validate_installation_tool",
    "validate_package_runtime_install",
    "validation_error_from_result",
    "wardn_hub_catalog_url",
)
